import {
  AddFilled,
  AddRegular,
  AirplaneFilled,
  AirplaneRegular,
  AppsListDetailFilled,
  AppsListDetailRegular,
  AppsListFilled,
  AppsListRegular,
  ArrowClockwiseFilled,
  ArrowClockwiseRegular,
  ArrowDownFilled,
  ArrowDownRegular,
  ArrowDownloadFilled,
  ArrowDownloadRegular,
  ArrowExitFilled,
  ArrowExitRegular,
  ArrowLeftFilled,
  ArrowLeftRegular,
  ArrowResetFilled,
  ArrowResetRegular,
  ArrowRightFilled,
  ArrowRightRegular,
  ArrowReplyRegular,
  ArrowReplyFilled,
  ArrowSortFilled,
  ArrowSortRegular,
  ArrowSyncFilled,
  ArrowSyncRegular,
  ArrowUndoFilled,
  ArrowUndoRegular,
  ArrowUpFilled,
  ArrowUpRegular,
  AttachFilled,
  AttachRegular,
  CalendarAddFilled,
  CalendarAddRegular,
  CameraFilled,
  CameraRegular,
  CartFilled,
  CartRegular,
  ChatFilled,
  ChatRegular,
  CheckmarkCircleFilled,
  CheckmarkCircleRegular,
  CheckmarkFilled,
  CheckmarkRegular,
  ChevronDownFilled,
  ChevronDownRegular,
  ChevronLeftFilled,
  ChevronLeftRegular,
  ChevronRightFilled,
  ChevronRightRegular,
  ChevronUpFilled,
  ChevronUpRegular,
  CircleFilled,
  CircleRegular,
  ClockAlarmFilled,
  ClockAlarmRegular,
  ClockFilled,
  ClockRegular,
  CopyFilled,
  CopyRegular,
  DatabaseFilled,
  DatabaseRegular,
  DeleteFilled,
  DeleteRegular,
  DismissCircleFilled,
  DismissCircleRegular,
  DismissFilled,
  DismissRegular,
  DocumentAddFilled,
  DocumentAddRegular,
  DocumentBulletListFilled,
  DocumentBulletListRegular,
  DocumentFilled,
  DocumentPdfFilled,
  DocumentPdfRegular,
  DocumentRegular,
  EditFilled,
  EditRegular,
  EmojiSmileSlightFilled,
  EmojiSmileSlightRegular,
  EraserFilled,
  EraserRegular,
  ErrorCircleFilled,
  ErrorCircleRegular,
  EyeFilled,
  EyeRegular,
  FilterFilled,
  FilterRegular,
  GlobeProhibitedRegular,
  GlobeProhibitedFilled,
  GlobeRegular,
  GlobeFilled,
  GridDotsFilled,
  GridDotsRegular,
  HistoryFilled,
  HistoryRegular,
  HomeFilled,
  HomeRegular,
  InfoFilled,
  InfoRegular,
  LinkFilled,
  LinkRegular,
  MailFilled,
  MailRegular,
  MoneyFilled,
  MoneyRegular,
  MoreHorizontalFilled,
  MoreHorizontalRegular,
  OpenFilled,
  OpenRegular,
  PeopleAddFilled,
  PeopleAddRegular,
  PeopleFilled,
  PeopleRegular,
  PersonFilled,
  PersonRegular,
  PrintFilled,
  PrintRegular,
  QuestionFilled,
  QuestionRegular,
  SaveCopyFilled,
  SaveCopyRegular,
  SaveFilled,
  SaveRegular,
  SearchFilled,
  SearchRegular,
  SendFilled,
  SendRegular,
  ShareRegular,
  ShareFilled,
  ServiceBellFilled,
  ServiceBellRegular,
  SettingsFilled,
  SettingsRegular,
  TextCaseTitleFilled,
  TextCaseTitleRegular,
  WarningFilled,
  WarningRegular,
} from "@fluentui/react-icons";

export const FluentIcons = {
  AddFilled: AddFilled,
  AddRegular: AddRegular,
  AirplaneFilled: AirplaneFilled,
  AirplaneRegular: AirplaneRegular,
  AppsListDetailFilled: AppsListDetailFilled,
  AppsListDetailRegular: AppsListDetailRegular,
  AppsListFilled: AppsListFilled,
  AppsListRegular: AppsListRegular,
  ArrowClockwiseFilled: ArrowClockwiseFilled,
  ArrowClockwiseRegular: ArrowClockwiseRegular,
  ArrowDownFilled: ArrowDownFilled,
  ArrowDownloadFilled: ArrowDownloadFilled,
  ArrowDownloadRegular: ArrowDownloadRegular,
  ArrowDownRegular: ArrowDownRegular,
  ArrowExitFilled: ArrowExitFilled,
  ArrowExitRegular: ArrowExitRegular,
  ArrowLeftFilled: ArrowLeftFilled,
  ArrowLeftRegular: ArrowLeftRegular,
  ArrowReplyRegular: ArrowReplyRegular,
  ArrowReplyFilled: ArrowReplyFilled,
  ArrowResetFilled: ArrowResetFilled,
  ArrowResetRegular: ArrowResetRegular,
  ArrowRightFilled: ArrowRightFilled,
  ArrowRightRegular: ArrowRightRegular,
  ArrowSortFilled: ArrowSortFilled,
  ArrowSortRegular: ArrowSortRegular,
  ArrowSyncFilled: ArrowSyncFilled,
  ArrowSyncRegular: ArrowSyncRegular,
  ArrowUndoFilled: ArrowUndoFilled,
  ArrowUndoRegular: ArrowUndoRegular,
  ArrowUpFilled: ArrowUpFilled,
  ArrowUpRegular: ArrowUpRegular,
  AttachFilled: AttachFilled,
  AttachRegular: AttachRegular,
  CalendarAddFilled: CalendarAddFilled,
  CalendarAddRegular: CalendarAddRegular,
  CameraFilled: CameraFilled,
  CameraRegular: CameraRegular,
  CartFilled: CartFilled,
  CartRegular: CartRegular,
  ChatFilled: ChatFilled,
  ChatRegular: ChatRegular,
  CheckmarkCircleFilled: CheckmarkCircleFilled,
  CheckmarkCircleRegular: CheckmarkCircleRegular,
  CheckmarkFilled: CheckmarkFilled,
  CheckmarkRegular: CheckmarkRegular,
  ChevronDownFilled: ChevronDownFilled,
  ChevronDownRegular: ChevronDownRegular,
  ChevronLeftFilled: ChevronLeftFilled,
  ChevronLeftRegular: ChevronLeftRegular,
  ChevronRightFilled: ChevronRightFilled,
  ChevronRightRegular: ChevronRightRegular,
  ChevronUpFilled: ChevronUpFilled,
  ChevronUpRegular: ChevronUpRegular,
  CircleFilled: CircleFilled,
  CircleRegular: CircleRegular,
  ClockAlarmFilled: ClockAlarmFilled,
  ClockAlarmRegular: ClockAlarmRegular,
  ClockFilled: ClockFilled,
  ClockRegular: ClockRegular,
  CopyFilled: CopyFilled,
  CopyRegular: CopyRegular,
  DatabaseFilled: DatabaseFilled,
  DatabaseRegular: DatabaseRegular,
  DeleteFilled: DeleteFilled,
  DeleteRegular: DeleteRegular,
  DismissCircleFilled: DismissCircleFilled,
  DismissCircleRegular: DismissCircleRegular,
  DismissFilled: DismissFilled,
  DismissRegular: DismissRegular,
  DocumentAddFilled: DocumentAddFilled,
  DocumentAddRegular: DocumentAddRegular,
  DocumentBulletListFilled: DocumentBulletListFilled,
  DocumentBulletListRegular: DocumentBulletListRegular,
  DocumentFilled: DocumentFilled,
  DocumentPdfFilled: DocumentPdfFilled,
  DocumentPdfRegular: DocumentPdfRegular,
  DocumentRegular: DocumentRegular,
  EditFilled: EditFilled,
  EditRegular: EditRegular,
  EmojiSmileSlightFilled: EmojiSmileSlightFilled,
  EmojiSmileSlightRegular: EmojiSmileSlightRegular,
  EraserFilled: EraserFilled,
  EraserRegular: EraserRegular,
  ErrorCircleFilled: ErrorCircleFilled,
  ErrorCircleRegular: ErrorCircleRegular,
  EyeFilled: EyeFilled,
  EyeRegular: EyeRegular,
  FilterFilled: FilterFilled,
  FilterRegular: FilterRegular,
  GlobeProhibitedRegular: GlobeProhibitedRegular,
  GlobeProhibitedFilled: GlobeProhibitedFilled,
  GlobeRegular: GlobeRegular,
  GlobeFilled: GlobeFilled,
  GridDotsFilled: GridDotsFilled,
  GridDotsRegular: GridDotsRegular,
  HistoryFilled: HistoryFilled,
  HistoryRegular: HistoryRegular,
  HomeFilled: HomeFilled,
  HomeRegular: HomeRegular,
  InfoFilled: InfoFilled,
  InfoRegular: InfoRegular,
  LinkFilled: LinkFilled,
  LinkRegular: LinkRegular,
  MailFilled: MailFilled,
  MailRegular: MailRegular,
  MoneyFilled: MoneyFilled,
  MoneyRegular: MoneyRegular,
  MoreHorizontalFilled: MoreHorizontalFilled,
  MoreHorizontalRegular: MoreHorizontalRegular,
  OpenFilled: OpenFilled,
  OpenRegular: OpenRegular,
  PeopleAddFilled: PeopleAddFilled,
  PeopleAddRegular: PeopleAddRegular,
  PeopleFilled: PeopleFilled,
  PeopleRegular: PeopleRegular,
  PersonFilled: PersonFilled,
  PersonRegular: PersonRegular,
  PrintFilled: PrintFilled,
  PrintRegular: PrintRegular,
  QuestionFilled: QuestionFilled,
  QuestionRegular: QuestionRegular,
  SaveCopyFilled: SaveCopyFilled,
  SaveCopyRegular: SaveCopyRegular,
  SaveFilled: SaveFilled,
  SaveRegular: SaveRegular,
  SearchFilled: SearchFilled,
  SearchRegular: SearchRegular,
  SendFilled: SendFilled,
  SendRegular: SendRegular,
  ServiceBellFilled: ServiceBellFilled,
  ServiceBellRegular: ServiceBellRegular,
  SettingsFilled: SettingsFilled,
  SettingsRegular: SettingsRegular,
  ShareRegular: ShareRegular,
  ShareFilled: ShareFilled,
  TextCaseTitleFilled: TextCaseTitleFilled,
  TextCaseTitleRegular: TextCaseTitleRegular,
  WarningFilled: WarningFilled,
  WarningRegular: WarningRegular,
};
