define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Януари',
        DatePickerMonthShortJanuary: 'Януари',
        DatePickerMonthLongFebruary: 'Февруари',
        DatePickerMonthShortFebruary: 'Февруари',
        DatePickerMonthLongMarch: 'Март',
        DatePickerMonthShortMarch: 'Мар',
        DatePickerMonthLongApril: 'Април',
        DatePickerMonthShortApril: 'Април',
        DatePickerMonthLongMay: 'Може',
        DatePickerMonthShortMay: 'Може',
        DatePickerMonthLongJune: 'Юни',
        DatePickerMonthShortJune: 'Юни',
        DatePickerMonthLongJuly: 'Юли',
        DatePickerMonthShortJuly: 'Юли',
        DatePickerMonthLongAugust: 'Август',
        DatePickerMonthShortAugust: 'Август',
        DatePickerMonthLongSeptember: 'Септември',
        DatePickerMonthShortSeptember: 'Седем',
        DatePickerMonthLongOctober: 'Октомври',
        DatePickerMonthShortOctober: 'Октомври',
        DatePickerMonthLongNovember: 'Ноември',
        DatePickerMonthShortNovember: 'Ноември',
        DatePickerMonthLongDecember: 'Декември',
        DatePickerMonthShortDecember: 'Декември',
        DatePickerDayLongSunday: 'Неделя',
        DatePickerDayShortSunday: 'Слънцето',
        DatePickerDayLongMonday: 'Понеделник',
        DatePickerDayShortMonday: 'Ми',
        DatePickerDayLongTuesday: 'Вторник',
        DatePickerDayShortTuesday: 'Вт',
        DatePickerDayLongWednesday: 'Сряда',
        DatePickerDayShortWednesday: 'Ср',
        DatePickerDayLongThursday: 'Четвъртък',
        DatePickerDayShortThursday: 'Чт',
        DatePickerDayLongFriday: 'Петък',
        DatePickerDayShortFriday: 'Пт',
        DatePickerDayLongSaturday: 'Събота',
        DatePickerDayShortSaturday: 'Сб',
        DatePickerGoToToday: 'Днес',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Дата',
        DateTimePickerTime: 'Време',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Неправилна стойност на час',
        DateTimePickerMinuteValueInvalid: 'Неправилна стойност на минута',
        DateTimePickerSecondValueInvalid: 'Неправилна втора стойност',
        DateTimePickerTextErrorMessage: 'Моля, въведете валидна дата',
    };
});
