define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Gener',
        DatePickerMonthShortJanuary: 'Gener',
        DatePickerMonthLongFebruary: 'Febrer',
        DatePickerMonthShortFebruary: 'Febrer',
        DatePickerMonthLongMarch: 'Març',
        DatePickerMonthShortMarch: 'Espatllar',
        DatePickerMonthLongApril: 'Abril',
        DatePickerMonthShortApril: 'Abr',
        DatePickerMonthLongMay: 'Pot',
        DatePickerMonthShortMay: 'Pot',
        DatePickerMonthLongJune: 'Juny',
        DatePickerMonthShortJune: 'Juny',
        DatePickerMonthLongJuly: 'Juliol',
        DatePickerMonthShortJuly: 'Juliol',
        DatePickerMonthLongAugust: 'Agost',
        DatePickerMonthShortAugust: 'Agost',
        DatePickerMonthLongSeptember: 'Setembre',
        DatePickerMonthShortSeptember: 'Set',
        DatePickerMonthLongOctober: 'Octubre',
        DatePickerMonthShortOctober: 'Octubre',
        DatePickerMonthLongNovember: 'Novembre',
        DatePickerMonthShortNovember: 'Novembre',
        DatePickerMonthLongDecember: 'Desembre',
        DatePickerMonthShortDecember: 'Desembre',
        DatePickerDayLongSunday: 'Diumenge',
        DatePickerDayShortSunday: 'Sol',
        DatePickerDayLongMonday: 'Dilluns',
        DatePickerDayShortMonday: 'Meu',
        DatePickerDayLongTuesday: 'Dimarts',
        DatePickerDayShortTuesday: 'Dm',
        DatePickerDayLongWednesday: 'Dimecres',
        DatePickerDayShortWednesday: 'Dc',
        DatePickerDayLongThursday: 'Dijous',
        DatePickerDayShortThursday: 'Dij',
        DatePickerDayLongFriday: 'Divendres',
        DatePickerDayShortFriday: 'Dv',
        DatePickerDayLongSaturday: 'Dissabte',
        DatePickerDayShortSaturday: 'Ds',
        DatePickerGoToToday: 'Avui',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Data',
        DateTimePickerTime: 'Temps',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: "Valor d'hora incorrecte",
        DateTimePickerMinuteValueInvalid: 'Valor de minut incorrecte',
        DateTimePickerSecondValueInvalid: 'Segon valor incorrecte',
        DateTimePickerTextErrorMessage: 'Introduïu una data vàlida',
    };
});
