define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Januar',
        DatePickerMonthShortJanuary: 'Jan',
        DatePickerMonthLongFebruary: 'Februar',
        DatePickerMonthShortFebruary: 'Februar',
        DatePickerMonthLongMarch: 'Marts',
        DatePickerMonthShortMarch: 'Mar',
        DatePickerMonthLongApril: 'April',
        DatePickerMonthShortApril: 'Apr',
        DatePickerMonthLongMay: 'Kan',
        DatePickerMonthShortMay: 'Kan',
        DatePickerMonthLongJune: 'Juni',
        DatePickerMonthShortJune: 'Juni',
        DatePickerMonthLongJuly: 'Juli',
        DatePickerMonthShortJuly: 'Jul',
        DatePickerMonthLongAugust: 'August',
        DatePickerMonthShortAugust: 'August',
        DatePickerMonthLongSeptember: 'September',
        DatePickerMonthShortSeptember: 'Syv',
        DatePickerMonthLongOctober: 'Oktober',
        DatePickerMonthShortOctober: 'Oktober',
        DatePickerMonthLongNovember: 'November',
        DatePickerMonthShortNovember: 'November',
        DatePickerMonthLongDecember: 'December',
        DatePickerMonthShortDecember: 'December',
        DatePickerDayLongSunday: 'Søndag',
        DatePickerDayShortSunday: 'Sun',
        DatePickerDayLongMonday: 'Mandag',
        DatePickerDayShortMonday: 'Min',
        DatePickerDayLongTuesday: 'Tirsdag',
        DatePickerDayShortTuesday: 'Tue',
        DatePickerDayLongWednesday: 'Onsdag',
        DatePickerDayShortWednesday: 'Ons',
        DatePickerDayLongThursday: 'Torsdag',
        DatePickerDayShortThursday: 'Tor',
        DatePickerDayLongFriday: 'Fredag',
        DatePickerDayShortFriday: 'Fre',
        DatePickerDayLongSaturday: 'Lørdag',
        DatePickerDayShortSaturday: 'Lør',
        DatePickerGoToToday: 'Dag',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Dato',
        DateTimePickerTime: 'Tid',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Forkert time værdi',
        DateTimePickerMinuteValueInvalid: 'Forkert minutværdi',
        DateTimePickerSecondValueInvalid: 'Forkert anden værdi',
        DateTimePickerTextErrorMessage: 'Angiv en gyldig dato',
    };
});
