define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Januar',
        DatePickerMonthShortJanuary: 'Jan',
        DatePickerMonthLongFebruary: 'Februar',
        DatePickerMonthShortFebruary: 'Feb',
        DatePickerMonthLongMarch: 'März',
        DatePickerMonthShortMarch: 'Mär',
        DatePickerMonthLongApril: 'April',
        DatePickerMonthShortApril: 'Apr',
        DatePickerMonthLongMay: 'Mai',
        DatePickerMonthShortMay: 'Mai',
        DatePickerMonthLongJune: 'Juni',
        DatePickerMonthShortJune: 'Juni',
        DatePickerMonthLongJuly: 'Juli',
        DatePickerMonthShortJuly: 'Juli',
        DatePickerMonthLongAugust: 'August',
        DatePickerMonthShortAugust: 'Aug',
        DatePickerMonthLongSeptember: 'September',
        DatePickerMonthShortSeptember: 'Sep',
        DatePickerMonthLongOctober: 'Oktober',
        DatePickerMonthShortOctober: 'Okt',
        DatePickerMonthLongNovember: 'November',
        DatePickerMonthShortNovember: 'Nov',
        DatePickerMonthLongDecember: 'Dezember',
        DatePickerMonthShortDecember: 'Dez',
        DatePickerDayLongSunday: 'Sonntag',
        DatePickerDayShortSunday: 'So',
        DatePickerDayLongMonday: 'Montag',
        DatePickerDayShortMonday: 'Mo',
        DatePickerDayLongTuesday: 'Dienstag',
        DatePickerDayShortTuesday: 'Di',
        DatePickerDayLongWednesday: 'Mittwoch',
        DatePickerDayShortWednesday: 'Mi',
        DatePickerDayLongThursday: 'Donnerstag',
        DatePickerDayShortThursday: 'Do',
        DatePickerDayLongFriday: 'Freitag',
        DatePickerDayShortFriday: 'Fr',
        DatePickerDayLongSaturday: 'Samstag',
        DatePickerDayShortSaturday: 'Sa',
        DatePickerGoToToday: 'Heute',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Datum',
        DateTimePickerTime: 'Uhrzeit',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Falscher Stundenwert',
        DateTimePickerMinuteValueInvalid: 'Falscher Minutenwert',
        DateTimePickerSecondValueInvalid: 'Falscher zweiter Wert',
        DateTimePickerTextErrorMessage: 'Bitte geben Sie ein gültiges Datum ein',
    };
});
