define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Ιανουαρίου',
        DatePickerMonthShortJanuary: 'Ιανουαρίου',
        DatePickerMonthLongFebruary: 'Φεβρουάριος',
        DatePickerMonthShortFebruary: 'Φεβρουαρίου',
        DatePickerMonthLongMarch: 'Μαρτίου',
        DatePickerMonthShortMarch: 'Μαρ',
        DatePickerMonthLongApril: 'Απριλίου',
        DatePickerMonthShortApril: 'Απρ',
        DatePickerMonthLongMay: 'Μπορεί',
        DatePickerMonthShortMay: 'Μπορεί',
        DatePickerMonthLongJune: 'Ιουνίου',
        DatePickerMonthShortJune: 'Ιουνίου',
        DatePickerMonthLongJuly: 'Ιουλίου',
        DatePickerMonthShortJuly: 'Ιουλ',
        DatePickerMonthLongAugust: 'Αυγούστου',
        DatePickerMonthShortAugust: 'Αυγούστου',
        DatePickerMonthLongSeptember: 'Σεπτεμβρίου',
        DatePickerMonthShortSeptember: 'Επτά',
        DatePickerMonthLongOctober: 'Οκτωβρίου',
        DatePickerMonthShortOctober: 'Οκτωβρίου',
        DatePickerMonthLongNovember: 'Νοεμβρίου',
        DatePickerMonthShortNovember: 'Νοεμβρίου',
        DatePickerMonthLongDecember: 'Δεκεμβρίου',
        DatePickerMonthShortDecember: 'Δεκεμβρίου',
        DatePickerDayLongSunday: 'Κυριακή',
        DatePickerDayShortSunday: 'Κυρ',
        DatePickerDayLongMonday: 'Δευτέρα',
        DatePickerDayShortMonday: 'Μου',
        DatePickerDayLongTuesday: 'Τρίτη',
        DatePickerDayShortTuesday: 'Τρί',
        DatePickerDayLongWednesday: 'Τετάρτη',
        DatePickerDayShortWednesday: 'Τετ',
        DatePickerDayLongThursday: 'Πέμπτη',
        DatePickerDayShortThursday: 'Πέμ',
        DatePickerDayLongFriday: 'Παρασκευή',
        DatePickerDayShortFriday: 'Παρ',
        DatePickerDayLongSaturday: 'Σάββατο',
        DatePickerDayShortSaturday: 'Σάβ',
        DatePickerGoToToday: 'Σήμερα',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Ημερομηνία',
        DateTimePickerTime: 'Χρόνο',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Τιμή εσφαλμένης ώρας',
        DateTimePickerMinuteValueInvalid: 'Εσφαλμένη τιμή λεπτού',
        DateTimePickerSecondValueInvalid: 'Εσφαλμένη δεύτερη τιμή',
        DateTimePickerTextErrorMessage: 'Πληκτρολογήστε μια έγκυρη ημερομηνία',
    };
});
