define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Enero',
        DatePickerMonthShortJanuary: 'Ene',
        DatePickerMonthLongFebruary: 'Febrero',
        DatePickerMonthShortFebruary: 'Feb',
        DatePickerMonthLongMarch: 'Marzo',
        DatePickerMonthShortMarch: 'Mar',
        DatePickerMonthLongApril: 'Abril',
        DatePickerMonthShortApril: 'Abr',
        DatePickerMonthLongMay: 'Mayo',
        DatePickerMonthShortMay: 'May',
        DatePickerMonthLongJune: 'Junio',
        DatePickerMonthShortJune: 'Jun',
        DatePickerMonthLongJuly: 'Julio',
        DatePickerMonthShortJuly: 'Jul',
        DatePickerMonthLongAugust: 'Agosto',
        DatePickerMonthShortAugust: 'Ago',
        DatePickerMonthLongSeptember: 'Septiembre',
        DatePickerMonthShortSeptember: 'Sep',
        DatePickerMonthLongOctober: 'Octubre',
        DatePickerMonthShortOctober: 'Oct',
        DatePickerMonthLongNovember: 'Noviembre',
        DatePickerMonthShortNovember: 'Nov',
        DatePickerMonthLongDecember: 'Diciembre',
        DatePickerMonthShortDecember: 'Dic',
        DatePickerDayLongSunday: 'Domingo',
        DatePickerDayShortSunday: 'Dom',
        DatePickerDayLongMonday: 'Lunes',
        DatePickerDayShortMonday: 'Lun',
        DatePickerDayLongTuesday: 'Martes',
        DatePickerDayShortTuesday: 'Mar',
        DatePickerDayLongWednesday: 'Miércoles',
        DatePickerDayShortWednesday: 'Mié',
        DatePickerDayLongThursday: 'Jueves',
        DatePickerDayShortThursday: 'Jue',
        DatePickerDayLongFriday: 'Viernes',
        DatePickerDayShortFriday: 'Vie',
        DatePickerDayLongSaturday: 'Sábado',
        DatePickerDayShortSaturday: 'Sáb',
        DatePickerGoToToday: 'Hoy',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Fecha',
        DateTimePickerTime: 'hora',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Valor de hora incorrecto',
        DateTimePickerMinuteValueInvalid: 'Valor de minuto incorrecto',
        DateTimePickerSecondValueInvalid: 'Segundo valor incorrecto',
        DateTimePickerTextErrorMessage: 'Introduce una fecha válida',
    };
});
