define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Jaanuar',
        DatePickerMonthShortJanuary: 'Jaanuar',
        DatePickerMonthLongFebruary: 'Veebruar',
        DatePickerMonthShortFebruary: 'Veebruar',
        DatePickerMonthLongMarch: 'Märts',
        DatePickerMonthShortMarch: 'Märts',
        DatePickerMonthLongApril: 'Aprill',
        DatePickerMonthShortApril: 'Aprill',
        DatePickerMonthLongMay: 'Võib',
        DatePickerMonthShortMay: 'Võib',
        DatePickerMonthLongJune: 'Juuni',
        DatePickerMonthShortJune: 'Juuni',
        DatePickerMonthLongJuly: 'Juuli',
        DatePickerMonthShortJuly: 'Juuli',
        DatePickerMonthLongAugust: 'August',
        DatePickerMonthShortAugust: 'August',
        DatePickerMonthLongSeptember: 'September',
        DatePickerMonthShortSeptember: 'Seitse',
        DatePickerMonthLongOctober: 'Oktoober',
        DatePickerMonthShortOctober: 'Okt',
        DatePickerMonthLongNovember: 'November',
        DatePickerMonthShortNovember: 'Nov',
        DatePickerMonthLongDecember: 'Detsember',
        DatePickerMonthShortDecember: 'Dets',
        DatePickerDayLongSunday: 'Pühapäev',
        DatePickerDayShortSunday: 'Pühap',
        DatePickerDayLongMonday: 'Esmaspäev',
        DatePickerDayShortMonday: 'Minu',
        DatePickerDayLongTuesday: 'Teisipäev',
        DatePickerDayShortTuesday: 'T',
        DatePickerDayLongWednesday: 'Kolmapäev',
        DatePickerDayShortWednesday: 'K',
        DatePickerDayLongThursday: 'Neljapäev',
        DatePickerDayShortThursday: 'N',
        DatePickerDayLongFriday: 'Reede',
        DatePickerDayShortFriday: 'Reede',
        DatePickerDayLongSaturday: 'Laupäev',
        DatePickerDayShortSaturday: 'L',
        DatePickerGoToToday: 'Täna',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Kuupäev',
        DateTimePickerTime: 'Aeg',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Vale tundide väärtus',
        DateTimePickerMinuteValueInvalid: 'Vale minuti väärtus',
        DateTimePickerSecondValueInvalid: 'Vale teine väärtus',
        DateTimePickerTextErrorMessage: 'Sisestage sobiv kuupäev',
    };
});
