define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Tammikuu',
        DatePickerMonthShortJanuary: 'Tam',
        DatePickerMonthLongFebruary: 'Helmikuu',
        DatePickerMonthShortFebruary: 'Hel',
        DatePickerMonthLongMarch: 'Maaliskuu',
        DatePickerMonthShortMarch: 'Maal',
        DatePickerMonthLongApril: 'Huhtikuu',
        DatePickerMonthShortApril: 'Huhti',
        DatePickerMonthLongMay: 'Toukokuu',
        DatePickerMonthShortMay: 'Touko',
        DatePickerMonthLongJune: 'Kesäkuu',
        DatePickerMonthShortJune: 'Kesä',
        DatePickerMonthLongJuly: 'Heinäkuu',
        DatePickerMonthShortJuly: 'Heinä',
        DatePickerMonthLongAugust: 'Elokuu',
        DatePickerMonthShortAugust: 'Elo',
        DatePickerMonthLongSeptember: 'Syyskuu',
        DatePickerMonthShortSeptember: 'Syys',
        DatePickerMonthLongOctober: 'Lokakuu',
        DatePickerMonthShortOctober: 'Loka',
        DatePickerMonthLongNovember: 'Marraskuu',
        DatePickerMonthShortNovember: 'Marras',
        DatePickerMonthLongDecember: 'Joulukuu',
        DatePickerMonthShortDecember: 'Joulu',
        DatePickerDayLongSunday: 'Sunnuntai',
        DatePickerDayShortSunday: 'Sun',
        DatePickerDayLongMonday: 'Maanantai',
        DatePickerDayShortMonday: 'Ma',
        DatePickerDayLongTuesday: 'Tiistai',
        DatePickerDayShortTuesday: 'Ti',
        DatePickerDayLongWednesday: 'Keskiviikko',
        DatePickerDayShortWednesday: 'Ke',
        DatePickerDayLongThursday: 'Torstai',
        DatePickerDayShortThursday: 'To',
        DatePickerDayLongFriday: 'Perjantai',
        DatePickerDayShortFriday: 'Pe',
        DatePickerDayLongSaturday: 'Lauantai',
        DatePickerDayShortSaturday: 'La',
        DatePickerGoToToday: 'Tänään',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Päivämäärä',
        DateTimePickerTime: 'Aika',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Virheellinen tuntiarvo',
        DateTimePickerMinuteValueInvalid: 'Virheellinen minuuttiarvo',
        DateTimePickerSecondValueInvalid: 'Virheellinen toinen arvo',
        DateTimePickerTextErrorMessage: 'Anna kelvollinen päivämäärä',
    };
});
