define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Janvier',
        DatePickerMonthShortJanuary: 'Janv.',
        DatePickerMonthLongFebruary: 'Février',
        DatePickerMonthShortFebruary: 'Févr.',
        DatePickerMonthLongMarch: 'Mars',
        DatePickerMonthShortMarch: 'Mars',
        DatePickerMonthLongApril: 'Avril',
        DatePickerMonthShortApril: 'Avr.',
        DatePickerMonthLongMay: 'Mai',
        DatePickerMonthShortMay: 'Mai',
        DatePickerMonthLongJune: 'Juin',
        DatePickerMonthShortJune: 'Juin',
        DatePickerMonthLongJuly: 'Juillet',
        DatePickerMonthShortJuly: 'Juill.',
        DatePickerMonthLongAugust: 'Août',
        DatePickerMonthShortAugust: 'Août',
        DatePickerMonthLongSeptember: 'Septembre',
        DatePickerMonthShortSeptember: 'Sept.',
        DatePickerMonthLongOctober: 'Octobre',
        DatePickerMonthShortOctober: 'Oct.',
        DatePickerMonthLongNovember: 'Novembre',
        DatePickerMonthShortNovember: 'Nov.',
        DatePickerMonthLongDecember: 'Décembre',
        DatePickerMonthShortDecember: 'Déc.',
        DatePickerDayLongSunday: 'Dimanche',
        DatePickerDayShortSunday: 'Dim',
        DatePickerDayLongMonday: 'Lundi',
        DatePickerDayShortMonday: 'Lun',
        DatePickerDayLongTuesday: 'Mardi',
        DatePickerDayShortTuesday: 'Mar',
        DatePickerDayLongWednesday: 'Mercredi',
        DatePickerDayShortWednesday: 'Mer',
        DatePickerDayLongThursday: 'Jeudi',
        DatePickerDayShortThursday: 'Jeu',
        DatePickerDayLongFriday: 'Vendredi',
        DatePickerDayShortFriday: 'Ven',
        DatePickerDayLongSaturday: 'Samedi',
        DatePickerDayShortSaturday: 'Sam',
        DatePickerGoToToday: "Aujourd'hui",
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Date',
        DateTimePickerTime: 'Heure',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: "Valeur incorrecte pour l'heure",
        DateTimePickerMinuteValueInvalid: 'Valeur de minute incorrecte',
        DateTimePickerSecondValueInvalid: 'Deuxième valeur incorrecte',
        DateTimePickerTextErrorMessage: 'Veuillez saisir une date valide',
    };
});
