define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Január',
        DatePickerMonthShortJanuary: 'Jan',
        DatePickerMonthLongFebruary: 'Február',
        DatePickerMonthShortFebruary: 'Feb',
        DatePickerMonthLongMarch: 'Március',
        DatePickerMonthShortMarch: 'Már',
        DatePickerMonthLongApril: 'Április',
        DatePickerMonthShortApril: 'Ápr',
        DatePickerMonthLongMay: 'Május',
        DatePickerMonthShortMay: 'Máj',
        DatePickerMonthLongJune: 'Június',
        DatePickerMonthShortJune: 'Jún',
        DatePickerMonthLongJuly: 'Július',
        DatePickerMonthShortJuly: 'Júl',
        DatePickerMonthLongAugust: 'Augusztus',
        DatePickerMonthShortAugust: 'Aug',
        DatePickerMonthLongSeptember: 'Szeptember',
        DatePickerMonthShortSeptember: 'Szept',
        DatePickerMonthLongOctober: 'Október',
        DatePickerMonthShortOctober: 'Okt',
        DatePickerMonthLongNovember: 'November',
        DatePickerMonthShortNovember: 'Nov',
        DatePickerMonthLongDecember: 'December',
        DatePickerMonthShortDecember: 'Dec',
        DatePickerDayLongSunday: 'Vasárnap',
        DatePickerDayShortSunday: 'Vas',
        DatePickerDayLongMonday: 'Hétfő',
        DatePickerDayShortMonday: 'Hé',
        DatePickerDayLongTuesday: 'Kedd',
        DatePickerDayShortTuesday: 'Ke',
        DatePickerDayLongWednesday: 'Szerda',
        DatePickerDayShortWednesday: 'Sze',
        DatePickerDayLongThursday: 'Csütörtök',
        DatePickerDayShortThursday: 'Csü',
        DatePickerDayLongFriday: 'Péntek',
        DatePickerDayShortFriday: 'Pé',
        DatePickerDayLongSaturday: 'Szombat',
        DatePickerDayShortSaturday: 'Szo',
        DatePickerGoToToday: 'Ma',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Dátum',
        DateTimePickerTime: 'Idő',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Helytelen óra érték',
        DateTimePickerMinuteValueInvalid: 'Helytelen perc érték',
        DateTimePickerSecondValueInvalid: 'Helytelen másodperc érték',
        DateTimePickerTextErrorMessage: 'Helyes dátum értéket adjon meg',
    };
});