define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Gennaio',
        DatePickerMonthShortJanuary: 'Gennaio',
        DatePickerMonthLongFebruary: 'Febbraio',
        DatePickerMonthShortFebruary: 'Febbraio',
        DatePickerMonthLongMarch: 'Marzo',
        DatePickerMonthShortMarch: 'Mar',
        DatePickerMonthLongApril: 'Aprile',
        DatePickerMonthShortApril: 'Apr',
        DatePickerMonthLongMay: 'Maggio',
        DatePickerMonthShortMay: 'Maggio',
        DatePickerMonthLongJune: 'Giugno',
        DatePickerMonthShortJune: 'Giu',
        DatePickerMonthLongJuly: 'Luglio',
        DatePickerMonthShortJuly: 'Lug',
        DatePickerMonthLongAugust: 'Agosto',
        DatePickerMonthShortAugust: 'Agosto',
        DatePickerMonthLongSeptember: 'Settembre',
        DatePickerMonthShortSeptember: 'Sette',
        DatePickerMonthLongOctober: 'Ottobre',
        DatePickerMonthShortOctober: 'Ottobre',
        DatePickerMonthLongNovember: 'Novembre',
        DatePickerMonthShortNovember: 'Novembre',
        DatePickerMonthLongDecember: 'Dicembre',
        DatePickerMonthShortDecember: 'Dicembre',
        DatePickerDayLongSunday: 'Domenica',
        DatePickerDayShortSunday: 'sole',
        DatePickerDayLongMonday: 'Lunedì',
        DatePickerDayShortMonday: 'Mio',
        DatePickerDayLongTuesday: 'Martedì',
        DatePickerDayShortTuesday: 'Mar',
        DatePickerDayLongWednesday: 'Mercoledì',
        DatePickerDayShortWednesday: 'Mercoledì',
        DatePickerDayLongThursday: 'Giovedì',
        DatePickerDayShortThursday: 'Thu',
        DatePickerDayLongFriday: 'Venerdì',
        DatePickerDayShortFriday: 'Ven',
        DatePickerDayLongSaturday: 'Sabato',
        DatePickerDayShortSaturday: 'Sab',
        DatePickerGoToToday: 'Oggi',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Data',
        DateTimePickerTime: 'Tempo',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Valore orario errato',
        DateTimePickerMinuteValueInvalid: 'Valore minuto non corretto',
        DateTimePickerSecondValueInvalid: 'Secondo valore errato',
        DateTimePickerTextErrorMessage: 'Immettere una data valida',
    };
});
