define([], () => {
    return {
        DatePickerMonthLongJanuary: '1 月',
        DatePickerMonthShortJanuary: '1 月',
        DatePickerMonthLongFebruary: '2 月',
        DatePickerMonthShortFebruary: '2 月',
        DatePickerMonthLongMarch: '3 月',
        DatePickerMonthShortMarch: '3 月',
        DatePickerMonthLongApril: '4 月',
        DatePickerMonthShortApril: '4 月',
        DatePickerMonthLongMay: '5 月',
        DatePickerMonthShortMay: '5 月',
        DatePickerMonthLongJune: '6 月',
        DatePickerMonthShortJune: '6 月',
        DatePickerMonthLongJuly: '7 月',
        DatePickerMonthShortJuly: '7 月',
        DatePickerMonthLongAugust: '8 月',
        DatePickerMonthShortAugust: '8 月',
        DatePickerMonthLongSeptember: '9 月',
        DatePickerMonthShortSeptember: '9 月',
        DatePickerMonthLongOctober: '10 月',
        DatePickerMonthShortOctober: '10 月',
        DatePickerMonthLongNovember: '11 月',
        DatePickerMonthShortNovember: '11 月',
        DatePickerMonthLongDecember: '12 月',
        DatePickerMonthShortDecember: '12 月',
        DatePickerDayLongSunday: '日曜日',
        DatePickerDayShortSunday: '日',
        DatePickerDayLongMonday: '月曜日',
        DatePickerDayShortMonday: '月',
        DatePickerDayLongTuesday: '火曜日',
        DatePickerDayShortTuesday: '火',
        DatePickerDayLongWednesday: '水曜日',
        DatePickerDayShortWednesday: '水',
        DatePickerDayLongThursday: '木曜日',
        DatePickerDayShortThursday: '木',
        DatePickerDayLongFriday: '金曜日',
        DatePickerDayShortFriday: '金',
        DatePickerDayLongSaturday: '土曜日',
        DatePickerDayShortSaturday: '土',
        DatePickerGoToToday: '今日',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: '日付',
        DateTimePickerTime: '時間',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: '時間の値が正しくありません',
        DateTimePickerMinuteValueInvalid: '正しくない分の値',
        DateTimePickerSecondValueInvalid: '2 番目の値が正しくありません',
        DateTimePickerTextErrorMessage: '有効な日付を入力してください',
    };
});
