define([], () => {
    return {
        DatePickerMonthLongJanuary: 'sausis',
        DatePickerMonthShortJanuary: 'saus.',
        DatePickerMonthLongFebruary: 'vasaris',
        DatePickerMonthShortFebruary: 'vas.',
        DatePickerMonthLongMarch: 'kovas',
        DatePickerMonthShortMarch: 'kov.',
        DatePickerMonthLongApril: 'balandis',
        DatePickerMonthShortApril: 'bal.',
        DatePickerMonthLongMay: 'gegužė',
        DatePickerMonthShortMay: 'geg.',
        DatePickerMonthLongJune: 'birželis',
        DatePickerMonthShortJune: 'birž.',
        DatePickerMonthLongJuly: 'liepa',
        DatePickerMonthShortJuly: 'liep.',
        DatePickerMonthLongAugust: 'rugpjūtis',
        DatePickerMonthShortAugust: 'rugp.',
        DatePickerMonthLongSeptember: 'rugsėjis',
        DatePickerMonthShortSeptember: 'rugs.',
        DatePickerMonthLongOctober: 'spalis',
        DatePickerMonthShortOctober: 'spal.',
        DatePickerMonthLongNovember: 'lapkritis',
        DatePickerMonthShortNovember: 'lapkr.',
        DatePickerMonthLongDecember: 'gruodis',
        DatePickerMonthShortDecember: 'gruod.',
        DatePickerDayLongSunday: 'sekmadienis',
        DatePickerDayShortSunday: 'sk',
        DatePickerDayLongMonday: 'pirmadienis',
        DatePickerDayShortMonday: 'pr',
        DatePickerDayLongTuesday: 'antradienis',
        DatePickerDayShortTuesday: 'an',
        DatePickerDayLongWednesday: 'trečiadienis',
        DatePickerDayShortWednesday: 'tr',
        DatePickerDayLongThursday: 'ketvirtadienis',
        DatePickerDayShortThursday: 'kt',
        DatePickerDayLongFriday: 'penktadienis',
        DatePickerDayShortFriday: 'pn',
        DatePickerDayLongSaturday: 'šeštadienis',
        DatePickerDayShortSaturday: 'št',
        DatePickerGoToToday: 'šiandien',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Data',
        DateTimePickerTime: 'Laikas',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Netinkama laiko reikšmė',
        DateTimePickerMinuteValueInvalid: 'Neteisinga minutės reikšmė',
        DateTimePickerSecondValueInvalid: 'Neteisinga antroji reikšmė',
        DateTimePickerTextErrorMessage: 'Įveskite tinkamą datą',
    };
});
