define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Janvāris',
        DatePickerMonthShortJanuary: 'Jan',
        DatePickerMonthLongFebruary: 'Februāris',
        DatePickerMonthShortFebruary: 'Februāris',
        DatePickerMonthLongMarch: 'Marts',
        DatePickerMonthShortMarch: 'Marts',
        DatePickerMonthLongApril: 'Aprīlis',
        DatePickerMonthShortApril: 'Apr',
        DatePickerMonthLongMay: 'Var',
        DatePickerMonthShortMay: 'Var',
        DatePickerMonthLongJune: 'Jūnijs',
        DatePickerMonthShortJune: 'Jūnijs',
        DatePickerMonthLongJuly: 'Jūlijs',
        DatePickerMonthShortJuly: 'Jūlijs',
        DatePickerMonthLongAugust: 'Augusts',
        DatePickerMonthShortAugust: 'Augusts',
        DatePickerMonthLongSeptember: 'Septembris',
        DatePickerMonthShortSeptember: 'Septiņas',
        DatePickerMonthLongOctober: 'Oktobris',
        DatePickerMonthShortOctober: 'Oktobris',
        DatePickerMonthLongNovember: 'Novembris',
        DatePickerMonthShortNovember: 'Novembris',
        DatePickerMonthLongDecember: 'Decembris',
        DatePickerMonthShortDecember: 'Decembris',
        DatePickerDayLongSunday: 'Svētdiena',
        DatePickerDayShortSunday: 'Saule',
        DatePickerDayLongMonday: 'Pirmdiena',
        DatePickerDayShortMonday: 'Manu',
        DatePickerDayLongTuesday: 'Otrdiena',
        DatePickerDayShortTuesday: 'Tue',
        DatePickerDayLongWednesday: 'Trešdiena',
        DatePickerDayShortWednesday: 'Wed',
        DatePickerDayLongThursday: 'Ceturtdiena',
        DatePickerDayShortThursday: 'Cet',
        DatePickerDayLongFriday: 'Piektdiena',
        DatePickerDayShortFriday: 'Fri',
        DatePickerDayLongSaturday: 'Sestdiena',
        DatePickerDayShortSaturday: 'Sestdiena',
        DatePickerGoToToday: 'Šodien',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Datumu',
        DateTimePickerTime: 'Laiku',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Nepareiza stundas vērtība',
        DateTimePickerMinuteValueInvalid: 'Nepareiza minūtes vērtība',
        DateTimePickerSecondValueInvalid: 'Nepareiza otrā vērtība',
        DateTimePickerTextErrorMessage: 'Lūdzu, ievadiet derīgu datumu',
    };
});
