define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Januar',
        DatePickerMonthShortJanuary: 'Jan',
        DatePickerMonthLongFebruary: 'Februar',
        DatePickerMonthShortFebruary: 'Feb',
        DatePickerMonthLongMarch: 'Mars',
        DatePickerMonthShortMarch: 'Mar',
        DatePickerMonthLongApril: 'April',
        DatePickerMonthShortApril: 'April',
        DatePickerMonthLongMay: 'Mai',
        DatePickerMonthShortMay: 'Mai',
        DatePickerMonthLongJune: 'Juni',
        DatePickerMonthShortJune: 'Juni',
        DatePickerMonthLongJuly: 'Juli',
        DatePickerMonthShortJuly: 'Juli',
        DatePickerMonthLongAugust: 'August',
        DatePickerMonthShortAugust: 'Aug',
        DatePickerMonthLongSeptember: 'September',
        DatePickerMonthShortSeptember: 'Sept',
        DatePickerMonthLongOctober: 'Oktober',
        DatePickerMonthShortOctober: 'Okt',
        DatePickerMonthLongNovember: 'November',
        DatePickerMonthShortNovember: 'Nov',
        DatePickerMonthLongDecember: 'Desember',
        DatePickerMonthShortDecember: 'Des',
        DatePickerDayLongSunday: 'Søndag',
        DatePickerDayShortSunday: 'Sø.',
        DatePickerDayLongMonday: 'Mandag',
        DatePickerDayShortMonday: 'Ma.',
        DatePickerDayLongTuesday: 'Tirsdag',
        DatePickerDayShortTuesday: 'Ti.',
        DatePickerDayLongWednesday: 'Onsdag',
        DatePickerDayShortWednesday: 'On.',
        DatePickerDayLongThursday: 'Torsdag',
        DatePickerDayShortThursday: 'To.',
        DatePickerDayLongFriday: 'Fredag',
        DatePickerDayShortFriday: 'Fr.',
        DatePickerDayLongSaturday: 'Lørdag',
        DatePickerDayShortSaturday: 'Lø.',
        DatePickerGoToToday: 'I dag',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Dato',
        DateTimePickerTime: 'Tid',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Feil timeverdi',
        DateTimePickerMinuteValueInvalid: 'Feil minuttverdi',
        DateTimePickerSecondValueInvalid: 'Feil sekundverdi',
        DateTimePickerTextErrorMessage: 'Angi en gyldig dato',
    };
});
