define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Januari',
        DatePickerMonthShortJanuary: 'Januari',
        DatePickerMonthLongFebruary: 'Februari',
        DatePickerMonthShortFebruary: 'Februari',
        DatePickerMonthLongMarch: 'Maart',
        DatePickerMonthShortMarch: 'Maa',
        DatePickerMonthLongApril: 'April',
        DatePickerMonthShortApril: 'Apr',
        DatePickerMonthLongMay: 'Mei',
        DatePickerMonthShortMay: 'Mei',
        DatePickerMonthLongJune: 'Juni',
        DatePickerMonthShortJune: 'Jr',
        DatePickerMonthLongJuly: 'Juli',
        DatePickerMonthShortJuly: 'Jul',
        DatePickerMonthLongAugust: 'Augustus',
        DatePickerMonthShortAugust: 'Augustus',
        DatePickerMonthLongSeptember: 'September',
        DatePickerMonthShortSeptember: 'Zeven',
        DatePickerMonthLongOctober: 'Oktober',
        DatePickerMonthShortOctober: 'Okt',
        DatePickerMonthLongNovember: 'November',
        DatePickerMonthShortNovember: 'November',
        DatePickerMonthLongDecember: 'December',
        DatePickerMonthShortDecember: 'Dec',
        DatePickerDayLongSunday: 'Zondag',
        DatePickerDayShortSunday: 'Zon',
        DatePickerDayLongMonday: 'Maandag',
        DatePickerDayShortMonday: 'Maa',
        DatePickerDayLongTuesday: 'Dinsdag',
        DatePickerDayShortTuesday: 'Din',
        DatePickerDayLongWednesday: 'Woensdag',
        DatePickerDayShortWednesday: 'Woe',
        DatePickerDayLongThursday: 'Donderdag',
        DatePickerDayShortThursday: 'Don',
        DatePickerDayLongFriday: 'Vrijdag',
        DatePickerDayShortFriday: 'Vri',
        DatePickerDayLongSaturday: 'Zaterdag',
        DatePickerDayShortSaturday: 'Zat',
        DatePickerGoToToday: 'Vandaag',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Dag',
        DateTimePickerTime: 'Tijd',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Foute uur waarde',
        DateTimePickerMinuteValueInvalid: 'Onjuiste minuutwaarde',
        DateTimePickerSecondValueInvalid: 'Onjuiste tweede waarde',
        DateTimePickerTextErrorMessage: 'Voer een geldige datum in',
    };
});
