define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Stycznia',
        DatePickerMonthShortJanuary: 'Jan',
        DatePickerMonthLongFebruary: 'Lut',
        DatePickerMonthShortFebruary: 'Lutego',
        DatePickerMonthLongMarch: 'Mar',
        DatePickerMonthShortMarch: 'Marzec',
        DatePickerMonthLongApril: 'Kwietnia',
        DatePickerMonthShortApril: 'Kwiecień',
        DatePickerMonthLongMay: 'Może',
        DatePickerMonthShortMay: 'Może',
        DatePickerMonthLongJune: 'Czerwca',
        DatePickerMonthShortJune: 'Cze',
        DatePickerMonthLongJuly: 'Lipca',
        DatePickerMonthShortJuly: 'Lip',
        DatePickerMonthLongAugust: 'Sierpnia',
        DatePickerMonthShortAugust: 'Sierpnia',
        DatePickerMonthLongSeptember: 'Września',
        DatePickerMonthShortSeptember: 'Siedem',
        DatePickerMonthLongOctober: 'Października',
        DatePickerMonthShortOctober: 'Października',
        DatePickerMonthLongNovember: 'Listopada',
        DatePickerMonthShortNovember: 'Listopada',
        DatePickerMonthLongDecember: 'Grudnia',
        DatePickerMonthShortDecember: 'Grudnia',
        DatePickerDayLongSunday: 'Niedziela',
        DatePickerDayShortSunday: 'Słońce',
        DatePickerDayLongMonday: 'Poniedziałek',
        DatePickerDayShortMonday: 'Mój',
        DatePickerDayLongTuesday: 'Wtorek',
        DatePickerDayShortTuesday: 'Wt',
        DatePickerDayLongWednesday: 'Środa',
        DatePickerDayShortWednesday: 'Śr',
        DatePickerDayLongThursday: 'Czwartek',
        DatePickerDayShortThursday: 'Czw',
        DatePickerDayLongFriday: 'Piątek',
        DatePickerDayShortFriday: 'Pt',
        DatePickerDayLongSaturday: 'Sobota',
        DatePickerDayShortSaturday: 'Sob',
        DatePickerGoToToday: 'Dziś',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Data',
        DateTimePickerTime: 'Czas',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Nieprawidłowa wartość godziny',
        DateTimePickerMinuteValueInvalid: 'Nieprawidłowa wartość minutowa',
        DateTimePickerSecondValueInvalid: 'Nieprawidłowa druga wartość',
        DateTimePickerTextErrorMessage: 'Podaj prawidłową datę',
    };
});
