define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Janeiro',
        DatePickerMonthShortJanuary: 'Jan',
        DatePickerMonthLongFebruary: 'Fevereiro',
        DatePickerMonthShortFebruary: 'Fev',
        DatePickerMonthLongMarch: 'Março',
        DatePickerMonthShortMarch: 'Mar',
        DatePickerMonthLongApril: 'Abril',
        DatePickerMonthShortApril: 'Abr',
        DatePickerMonthLongMay: 'Maio',
        DatePickerMonthShortMay: 'Mai',
        DatePickerMonthLongJune: 'Junho',
        DatePickerMonthShortJune: 'Jun',
        DatePickerMonthLongJuly: 'Julho',
        DatePickerMonthShortJuly: 'Jul',
        DatePickerMonthLongAugust: 'Agosto',
        DatePickerMonthShortAugust: 'Ago',
        DatePickerMonthLongSeptember: 'Setembro',
        DatePickerMonthShortSeptember: 'Set',
        DatePickerMonthLongOctober: 'Outubro',
        DatePickerMonthShortOctober: 'Out',
        DatePickerMonthLongNovember: 'Novembro',
        DatePickerMonthShortNovember: 'Nov',
        DatePickerMonthLongDecember: 'Dezembro',
        DatePickerMonthShortDecember: 'Dez',
        DatePickerDayLongSunday: 'Domingo',
        DatePickerDayShortSunday: 'Dom',
        DatePickerDayLongMonday: 'Segunda-feira',
        DatePickerDayShortMonday: 'Seg',
        DatePickerDayLongTuesday: 'Terça-feira',
        DatePickerDayShortTuesday: 'Ter',
        DatePickerDayLongWednesday: 'Quarta-feira',
        DatePickerDayShortWednesday: 'Qua',
        DatePickerDayLongThursday: 'Quinta-feira',
        DatePickerDayShortThursday: 'Qui',
        DatePickerDayLongFriday: 'Sexta-feira',
        DatePickerDayShortFriday: 'Sex',
        DatePickerDayLongSaturday: 'Sábado',
        DatePickerDayShortSaturday: 'Sáb',
        DatePickerGoToToday: 'Hoje',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Data',
        DateTimePickerTime: 'Tempo',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Valor de hora incorreto',
        DateTimePickerMinuteValueInvalid: 'Valor de minutos incorreto',
        DateTimePickerSecondValueInvalid: 'Valor de segundos incorreto',
        DateTimePickerTextErrorMessage: 'Por favor, insira uma data válida',
    };
});
