define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Ianuarie',
        DatePickerMonthShortJanuary: 'Ianuarie',
        DatePickerMonthLongFebruary: 'Februarie',
        DatePickerMonthShortFebruary: 'Februarie',
        DatePickerMonthLongMarch: 'Martie',
        DatePickerMonthShortMarch: 'Mar',
        DatePickerMonthLongApril: 'Aprilie',
        DatePickerMonthShortApril: 'Apr',
        DatePickerMonthLongMay: 'Pot',
        DatePickerMonthShortMay: 'Pot',
        DatePickerMonthLongJune: 'Iunie',
        DatePickerMonthShortJune: 'Iun',
        DatePickerMonthLongJuly: 'Iulie',
        DatePickerMonthShortJuly: 'Iul',
        DatePickerMonthLongAugust: 'August',
        DatePickerMonthShortAugust: 'Aug',
        DatePickerMonthLongSeptember: 'Septembrie',
        DatePickerMonthShortSeptember: 'Şapte',
        DatePickerMonthLongOctober: 'Octombrie',
        DatePickerMonthShortOctober: 'Octombrie',
        DatePickerMonthLongNovember: 'Noiembrie',
        DatePickerMonthShortNovember: 'Noiembrie',
        DatePickerMonthLongDecember: 'Decembrie',
        DatePickerMonthShortDecember: 'Decembrie',
        DatePickerDayLongSunday: 'Duminică',
        DatePickerDayShortSunday: 'Dum',
        DatePickerDayLongMonday: 'Luni',
        DatePickerDayShortMonday: 'Meu',
        DatePickerDayLongTuesday: 'Marţi',
        DatePickerDayShortTuesday: 'Mar',
        DatePickerDayLongWednesday: 'Miercuri',
        DatePickerDayShortWednesday: 'Mier',
        DatePickerDayLongThursday: 'Joi',
        DatePickerDayShortThursday: 'Joi',
        DatePickerDayLongFriday: 'Vineri',
        DatePickerDayShortFriday: 'Vineri',
        DatePickerDayLongSaturday: 'Sâmbătă',
        DatePickerDayShortSaturday: 'Sâm',
        DatePickerGoToToday: 'Astăzi',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Data',
        DateTimePickerTime: 'Timp',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Valoare oră incorectă',
        DateTimePickerMinuteValueInvalid: 'Valoare incorectă a minutei',
        DateTimePickerSecondValueInvalid: 'A doua valoare incorectă',
        DateTimePickerTextErrorMessage: 'Vă rugăm să introduceți o dată validă',
    };
});
