define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Январь',
        DatePickerMonthShortJanuary: 'Янв',
        DatePickerMonthLongFebruary: 'Февраль',
        DatePickerMonthShortFebruary: 'Фев',
        DatePickerMonthLongMarch: 'Март',
        DatePickerMonthShortMarch: 'Мар',
        DatePickerMonthLongApril: 'Апрель',
        DatePickerMonthShortApril: 'Апр',
        DatePickerMonthLongMay: 'Май',
        DatePickerMonthShortMay: 'Май',
        DatePickerMonthLongJune: 'Июнь',
        DatePickerMonthShortJune: 'Июн',
        DatePickerMonthLongJuly: 'Июль',
        DatePickerMonthShortJuly: 'Июл',
        DatePickerMonthLongAugust: 'Август',
        DatePickerMonthShortAugust: 'Авг',
        DatePickerMonthLongSeptember: 'Сентябрь',
        DatePickerMonthShortSeptember: 'Сен',
        DatePickerMonthLongOctober: 'Октябрь',
        DatePickerMonthShortOctober: 'Окт',
        DatePickerMonthLongNovember: 'Ноябрь',
        DatePickerMonthShortNovember: 'Ноя',
        DatePickerMonthLongDecember: 'Декабрь',
        DatePickerMonthShortDecember: 'Дек',
        DatePickerDayLongSunday: 'Воскресенье',
        DatePickerDayShortSunday: 'Вс',
        DatePickerDayLongMonday: 'Понедельник',
        DatePickerDayShortMonday: 'Пн',
        DatePickerDayLongTuesday: 'Вторник',
        DatePickerDayShortTuesday: 'Вт',
        DatePickerDayLongWednesday: 'Среда',
        DatePickerDayShortWednesday: 'Ср',
        DatePickerDayLongThursday: 'Четверг',
        DatePickerDayShortThursday: 'Чт',
        DatePickerDayLongFriday: 'Пятница',
        DatePickerDayShortFriday: 'Пт',
        DatePickerDayLongSaturday: 'Суббота',
        DatePickerDayShortSaturday: 'Сб',
        DatePickerGoToToday: 'Сегодня',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Дата',
        DateTimePickerTime: 'Время',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Значение часов введено неверно',
        DateTimePickerMinuteValueInvalid: 'Неверное значение минуты',
        DateTimePickerSecondValueInvalid: 'Неверное второе значение',
        DateTimePickerTextErrorMessage: 'Пожалуйста, введите действительную дату',
    };
});
