define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Január',
        DatePickerMonthShortJanuary: 'Jan',
        DatePickerMonthLongFebruary: 'Február',
        DatePickerMonthShortFebruary: 'Feb',
        DatePickerMonthLongMarch: 'Marec',
        DatePickerMonthShortMarch: 'Mar',
        DatePickerMonthLongApril: 'Apríl',
        DatePickerMonthShortApril: 'Apríla',
        DatePickerMonthLongMay: 'Máj',
        DatePickerMonthShortMay: 'Máj',
        DatePickerMonthLongJune: 'Jún',
        DatePickerMonthShortJune: 'Jún',
        DatePickerMonthLongJuly: 'Júl',
        DatePickerMonthShortJuly: 'Júl',
        DatePickerMonthLongAugust: 'August',
        DatePickerMonthShortAugust: 'Aug',
        DatePickerMonthLongSeptember: 'September',
        DatePickerMonthShortSeptember: 'Sep',
        DatePickerMonthLongOctober: 'Október',
        DatePickerMonthShortOctober: 'Okt',
        DatePickerMonthLongNovember: 'November',
        DatePickerMonthShortNovember: 'Nov',
        DatePickerMonthLongDecember: 'December',
        DatePickerMonthShortDecember: 'Dec',
        DatePickerDayLongSunday: 'Nedeľa',
        DatePickerDayShortSunday: 'Ne',
        DatePickerDayLongMonday: 'Pondelok',
        DatePickerDayShortMonday: 'Po',
        DatePickerDayLongTuesday: 'Utorok',
        DatePickerDayShortTuesday: 'Ut',
        DatePickerDayLongWednesday: 'Streda',
        DatePickerDayShortWednesday: 'St',
        DatePickerDayLongThursday: 'Štvrtok',
        DatePickerDayShortThursday: 'Št',
        DatePickerDayLongFriday: 'Piatok',
        DatePickerDayShortFriday: 'Pi',
        DatePickerDayLongSaturday: 'Sobotu',
        DatePickerDayShortSaturday: 'So',
        DatePickerGoToToday: 'Uskutočnená dnes o',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Dátum',
        DateTimePickerTime: 'Čas',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Nesprávna hodinová hodnota',
        DateTimePickerMinuteValueInvalid: 'Nesprávna minútová hodnota',
        DateTimePickerSecondValueInvalid: 'Nesprávna druhá hodnota',
        DateTimePickerTextErrorMessage: 'Zadajte platný dátum',
    };
});
