define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Januara',
        DatePickerMonthShortJanuary: 'Jan',
        DatePickerMonthLongFebruary: 'Februara',
        DatePickerMonthShortFebruary: 'Feb',
        DatePickerMonthLongMarch: 'Marta',
        DatePickerMonthShortMarch: 'Mar',
        DatePickerMonthLongApril: 'Aprila',
        DatePickerMonthShortApril: 'Apr',
        DatePickerMonthLongMay: 'Moћda',
        DatePickerMonthShortMay: 'Moћda',
        DatePickerMonthLongJune: 'Juna',
        DatePickerMonthShortJune: 'Dћun',
        DatePickerMonthLongJuly: 'Jula',
        DatePickerMonthShortJuly: 'Jul',
        DatePickerMonthLongAugust: 'Avgusta',
        DatePickerMonthShortAugust: 'Aug',
        DatePickerMonthLongSeptember: 'Septembra',
        DatePickerMonthShortSeptember: 'Sedam',
        DatePickerMonthLongOctober: 'Oktobra',
        DatePickerMonthShortOctober: 'Oct',
        DatePickerMonthLongNovember: 'Novembra',
        DatePickerMonthShortNovember: 'Nov',
        DatePickerMonthLongDecember: 'Decembra',
        DatePickerMonthShortDecember: 'Dec',
        DatePickerDayLongSunday: 'Nedelju',
        DatePickerDayShortSunday: 'Sunce',
        DatePickerDayLongMonday: 'Ponedeljak',
        DatePickerDayShortMonday: 'Moj',
        DatePickerDayLongTuesday: 'Utorak',
        DatePickerDayShortTuesday: 'Uto',
        DatePickerDayLongWednesday: 'Srede',
        DatePickerDayShortWednesday: 'Wed',
        DatePickerDayLongThursday: 'Иetvrtak',
        DatePickerDayShortThursday: 'Čet',
        DatePickerDayLongFriday: 'Petak',
        DatePickerDayShortFriday: 'Fri',
        DatePickerDayLongSaturday: 'Subotu',
        DatePickerDayShortSaturday: 'Sedeo',
        DatePickerGoToToday: 'Danas',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Datum',
        DateTimePickerTime: 'Vreme',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Netačna vrednost sata',
        DateTimePickerMinuteValueInvalid: 'Netačna minutna vrednost',
        DateTimePickerSecondValueInvalid: 'Netačna druga vrednost',
        DateTimePickerTextErrorMessage: 'Unesite važeći datum',
    };
});
