define([], () => {
    return {
        DatePickerMonthLongJanuary: 'januari',
        DatePickerMonthShortJanuary: 'jan',
        DatePickerMonthLongFebruary: 'februari',
        DatePickerMonthShortFebruary: 'feb',
        DatePickerMonthLongMarch: 'mars',
        DatePickerMonthShortMarch: 'mar',
        DatePickerMonthLongApril: 'april',
        DatePickerMonthShortApril: 'apr',
        DatePickerMonthLongMay: 'maj',
        DatePickerMonthShortMay: 'maj',
        DatePickerMonthLongJune: 'juni',
        DatePickerMonthShortJune: 'jun',
        DatePickerMonthLongJuly: 'juli',
        DatePickerMonthShortJuly: 'jul',
        DatePickerMonthLongAugust: 'augusti',
        DatePickerMonthShortAugust: 'aug',
        DatePickerMonthLongSeptember: 'september',
        DatePickerMonthShortSeptember: 'sep',
        DatePickerMonthLongOctober: 'oktober',
        DatePickerMonthShortOctober: 'okt',
        DatePickerMonthLongNovember: 'november',
        DatePickerMonthShortNovember: 'nov',
        DatePickerMonthLongDecember: 'december',
        DatePickerMonthShortDecember: 'dec',
        DatePickerDayLongSunday: 'söndag',
        DatePickerDayShortSunday: 'sön',
        DatePickerDayLongMonday: 'måndag',
        DatePickerDayShortMonday: 'mån',
        DatePickerDayLongTuesday: 'tisdag',
        DatePickerDayShortTuesday: 'tis',
        DatePickerDayLongWednesday: 'onsdag',
        DatePickerDayShortWednesday: 'ons',
        DatePickerDayLongThursday: 'torsdag',
        DatePickerDayShortThursday: 'tor',
        DatePickerDayLongFriday: 'fredag',
        DatePickerDayShortFriday: 'fre',
        DatePickerDayLongSaturday: 'lördag',
        DatePickerDayShortSaturday: 'lör',
        DatePickerGoToToday: 'Idag',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Datum',
        DateTimePickerTime: 'Tid',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Felaktigt timvärde',
        DateTimePickerMinuteValueInvalid: 'Felaktigt minutvärde',
        DateTimePickerSecondValueInvalid: 'Felaktigt andra värde',
        DateTimePickerTextErrorMessage: 'Ange ett giltigt datum',
    };
});
