define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Ocak',
        DatePickerMonthShortJanuary: 'Ocak',
        DatePickerMonthLongFebruary: 'Şubat',
        DatePickerMonthShortFebruary: 'Şubat',
        DatePickerMonthLongMarch: 'Mart',
        DatePickerMonthShortMarch: 'Mart',
        DatePickerMonthLongApril: 'Nisan',
        DatePickerMonthShortApril: 'Nisan',
        DatePickerMonthLongMay: 'Olabilir',
        DatePickerMonthShortMay: 'Olabilir',
        DatePickerMonthLongJune: 'Haziran',
        DatePickerMonthShortJune: 'Haziran',
        DatePickerMonthLongJuly: 'Temmuz',
        DatePickerMonthShortJuly: 'Temmuz',
        DatePickerMonthLongAugust: 'Ağustos',
        DatePickerMonthShortAugust: 'Ağustos',
        DatePickerMonthLongSeptember: 'Eylül',
        DatePickerMonthShortSeptember: 'Yedi',
        DatePickerMonthLongOctober: 'Ekim',
        DatePickerMonthShortOctober: 'Ekim',
        DatePickerMonthLongNovember: 'Kasım',
        DatePickerMonthShortNovember: 'Kasım',
        DatePickerMonthLongDecember: 'Aralık',
        DatePickerMonthShortDecember: 'Aralık',
        DatePickerDayLongSunday: 'Pazar',
        DatePickerDayShortSunday: 'Güneş',
        DatePickerDayLongMonday: 'Pazartesi',
        DatePickerDayShortMonday: 'Benim',
        DatePickerDayLongTuesday: 'Salı',
        DatePickerDayShortTuesday: 'Sal',
        DatePickerDayLongWednesday: 'Çarşamba',
        DatePickerDayShortWednesday: 'Çrş',
        DatePickerDayLongThursday: 'Perşembe',
        DatePickerDayShortThursday: 'Perşembe',
        DatePickerDayLongFriday: 'Cuma',
        DatePickerDayShortFriday: 'Fri',
        DatePickerDayLongSaturday: 'Cumartesi',
        DatePickerDayShortSaturday: 'Cumartesi',
        DatePickerGoToToday: 'Bugün',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Tarih',
        DateTimePickerTime: 'Zaman',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Yanlış saat değeri',
        DateTimePickerMinuteValueInvalid: 'Yanlış dakika değeri',
        DateTimePickerSecondValueInvalid: 'Yanlış ikinci değer',
        DateTimePickerTextErrorMessage: 'Lütfen geçerli bir tarih girin',
    };
});
