define([], () => {
    return {
        DatePickerMonthLongJanuary: 'Tháng',
        DatePickerMonthShortJanuary: 'Jan',
        DatePickerMonthLongFebruary: 'Ngày',
        DatePickerMonthShortFebruary: 'Tháng hai',
        DatePickerMonthLongMarch: 'Tháng',
        DatePickerMonthShortMarch: 'Mar',
        DatePickerMonthLongApril: 'Vào ngày',
        DatePickerMonthShortApril: 'Apr',
        DatePickerMonthLongMay: 'Có thể',
        DatePickerMonthShortMay: 'Có thể',
        DatePickerMonthLongJune: 'Vào ngày',
        DatePickerMonthShortJune: 'Jun',
        DatePickerMonthLongJuly: 'Vào ngày',
        DatePickerMonthShortJuly: 'Tháng bảy',
        DatePickerMonthLongAugust: 'Tháng tám',
        DatePickerMonthShortAugust: 'Tháng tám',
        DatePickerMonthLongSeptember: 'Tháng chín',
        DatePickerMonthShortSeptember: 'Bảy',
        DatePickerMonthLongOctober: 'Vào ngày',
        DatePickerMonthShortOctober: 'Tháng mười',
        DatePickerMonthLongNovember: 'Ngày',
        DatePickerMonthShortNovember: 'Ngày',
        DatePickerMonthLongDecember: 'Ngày',
        DatePickerMonthShortDecember: 'Tháng mười hai',
        DatePickerDayLongSunday: 'Chủ nhật',
        DatePickerDayShortSunday: 'Chủ nhật',
        DatePickerDayLongMonday: 'Thứ hai',
        DatePickerDayShortMonday: 'Của tôi',
        DatePickerDayLongTuesday: 'Thứ ba',
        DatePickerDayShortTuesday: 'Thứ sáu',
        DatePickerDayLongWednesday: 'Thứ tư',
        DatePickerDayShortWednesday: 'Thứ tư',
        DatePickerDayLongThursday: 'Thứ năm',
        DatePickerDayShortThursday: 'Thứ 5',
        DatePickerDayLongFriday: 'Thứ sáu',
        DatePickerDayShortFriday: 'Thứ sáu',
        DatePickerDayLongSaturday: 'Thứ bảy',
        DatePickerDayShortSaturday: 'Ngồi',
        DatePickerGoToToday: 'Nay',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: 'Ngày',
        DateTimePickerTime: 'Thời gian',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: 'Giá trị giờ không đúng',
        DateTimePickerMinuteValueInvalid: 'Giá trị phút không chính xác',
        DateTimePickerSecondValueInvalid: 'Giá trị thứ hai không chính xác',
        DateTimePickerTextErrorMessage: 'Vui lòng nhập ngày hợp lệ',
    };
});
