define([], () => {
    return {
        DatePickerMonthLongJanuary: '一月',
        DatePickerMonthShortJanuary: '1月',
        DatePickerMonthLongFebruary: '二月',
        DatePickerMonthShortFebruary: '2月',
        DatePickerMonthLongMarch: '三月',
        DatePickerMonthShortMarch: '三月',
        DatePickerMonthLongApril: '四月',
        DatePickerMonthShortApril: '四月',
        DatePickerMonthLongMay: '可能',
        DatePickerMonthShortMay: '可能',
        DatePickerMonthLongJune: '六月',
        DatePickerMonthShortJune: '君',
        DatePickerMonthLongJuly: '七月',
        DatePickerMonthShortJuly: '七月',
        DatePickerMonthLongAugust: '八月',
        DatePickerMonthShortAugust: '八月',
        DatePickerMonthLongSeptember: '九月',
        DatePickerMonthShortSeptember: '七',
        DatePickerMonthLongOctober: '十月',
        DatePickerMonthShortOctober: '10月',
        DatePickerMonthLongNovember: '十一月',
        DatePickerMonthShortNovember: '11 月',
        DatePickerMonthLongDecember: '十二月',
        DatePickerMonthShortDecember: '12 月',
        DatePickerDayLongSunday: '星期天',
        DatePickerDayShortSunday: '太陽',
        DatePickerDayLongMonday: '星期一',
        DatePickerDayShortMonday: '我',
        DatePickerDayLongTuesday: '星期二',
        DatePickerDayShortTuesday: '星期二',
        DatePickerDayLongWednesday: '星期三',
        DatePickerDayShortWednesday: '結婚',
        DatePickerDayLongThursday: '星期四',
        DatePickerDayShortThursday: '週四',
        DatePickerDayLongFriday: '星期五',
        DatePickerDayShortFriday: '週五',
        DatePickerDayLongSaturday: '星期六',
        DatePickerDayShortSaturday: '坐',
        DatePickerGoToToday: '今天',
        DatePickerIsRequiredErrorMessage: '',
        DatePickerInvalidInputErrorMessage: '',
        DatePickerIsOutOfBoundsErrorMessage: '',
        DateTimePickerDate: '日期',
        DateTimePickerTime: '時間',
        DateTimePickerTimeSeparator: ':',
        DateTimePickerHourValueInvalid: '小時值不正確',
        DateTimePickerMinuteValueInvalid: '不正確的分鐘值',
        DateTimePickerSecondValueInvalid: '不正確的第二個值',
        DateTimePickerTextErrorMessage: '請輸入有效日期',
    };
});
